### ISSUE TITLE
How to add lines?

### ISSUE THREAD

**Issue by jamescr** [BrunoSalerno/citylines#51]
What type of data "citylines" need to show info, for example from Costa Rica?

I have a GTFS file with data from Costa Rican Urban Train, is it useful?

**Comment by BrunoSalerno** [comment]
Hi @jamescr! Right now there is no way to load a GTFS file directly to citylines. The only way now to add features is using the built in editor. I can make some research to find a way to load GTFS files though.

**Comment by BrunoSalerno** [comment]
I'm closing this ticket until we have time to implement a file uploading system (that should be in another, specific, ticket actually)
