### ISSUE TITLE
Improve display when 2 lines on same track

### ISSUE THREAD

**Issue by Kalepom** [BrunoSalerno/citylines#85]
When two lines uses the same tracks or route, current display put one on the other and users don't get the actual information. Same thing for stations. 
![2017-08-10](https://user-images.githubusercontent.com/12937457/29182901-fa4e1c92-7e00-11e7-8c24-3263bd60244d.png)
There are 2 lines on the above picture, a blue and a red one. 

Can we imagine that when 2 routes or 2 stations are very close, it shows only 1 line hatched or dotted.
![2017-08-10 1](https://user-images.githubusercontent.com/12937457/29183194-0dd62a42-7e02-11e7-9f95-bbd3843d8cee.png)
Exemple on carto.metro map

**Comment by BrunoSalerno** [comment]
@Kalepom this is an important issue, I agree!

**Comment by BrunoSalerno** [comment]
@Kalepom I'm working on this!

<img width="567" alt="captura de pantalla 2017-11-18 a la s 14 01 12" src="https://user-images.githubusercontent.com/6061036/32982803-f9e3aa22-cc68-11e7-97eb-5133844ec2eb.png">
